#!/usr/bin/env bash

# Suitey Build Script
# This script bundles all source files and modules into a single executable suitey.sh

set -e

# Script version
SCRIPT_VERSION="0.1.0"

# Default output file
DEFAULT_OUTPUT="suitey.sh"

# Function to display usage information
show_usage() {
    cat << EOF
Suitey Build Script v${SCRIPT_VERSION}

Usage: $0 [OPTIONS]

Build the Suitey executable by bundling all source files and modules.

OPTIONS:
    -h, --help          Show this help message and exit
    -v, --version       Show version information and exit
    --output FILE       Specify output file (default: ${DEFAULT_OUTPUT})

EXAMPLES:
    $0                          # Build with default settings
    $0 --output my-suitey.sh    # Build with custom output file
    $0 --help                   # Show this help message

EOF
}

# Function to show version
show_version() {
    echo "Suitey Build Script v${SCRIPT_VERSION}"
}

# Function to log messages
log() {
    echo "[BUILD] $1" >&2
}

# Function to show error and exit
error() {
    echo "[ERROR] $1" >&2
    echo >&2
    echo "Run '$0 --help' for usage information." >&2
    exit 1
}

# Main build function
build_suitey() {
    local output_file="$1"

    log "Starting Suitey build process..."
    log "Output file: ${output_file}"

    # Create a temporary file for building
    local temp_file
    temp_file="$(mktemp)" || error "Failed to create temporary file"

    # Ensure temp file is cleaned up on exit
    trap "rm -f '$temp_file'" EXIT

    # Create the bundled script header
    log "Creating bundled script..."
    cat > "$temp_file" << 'EOF'
#!/usr/bin/env bash

# Suitey - Cross-platform test runner
# This file was generated by build.sh - do not edit directly

EOF

    # Add version information
    echo "# Version: ${SCRIPT_VERSION}" >> "$temp_file"
    echo "# Built: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> "$temp_file"
    echo "# Built on: $(uname -s) $(uname -r)" >> "$temp_file"
    echo >> "$temp_file"

    # Add main script content (placeholder for now)
    cat >> "$temp_file" << 'EOF'
# Main Suitey functionality will be added here

main() {
    echo "Suitey v0.1.0"
    echo "Build system test - functionality not yet implemented"
    echo ""
    echo "Usage: $0 [command] [options]"
    echo ""
    echo "Commands:"
    echo "  --help, -h    Show help"
    echo "  --version, -v Show version"
}

# Run main function
main "$@"
EOF

    # Move temp file to final location atomically
    if ! mv "$temp_file" "$output_file"; then
        error "Failed to create output file: $output_file"
    fi

    # Make the output file executable
    if ! chmod +x "$output_file"; then
        error "Failed to make output file executable: $output_file"
    fi

    # Verify the output file was created correctly
    if [[ ! -f "$output_file" ]]; then
        error "Output file was not created: $output_file"
    fi

    if [[ ! -x "$output_file" ]]; then
        error "Output file is not executable: $output_file"
    fi

    local file_size
    file_size=$(wc -c < "$output_file")
    log "Build completed successfully!"
    log "Output: ${output_file} (${file_size} bytes)"
}

# Validate output file path
validate_output_file() {
    local file="$1"

    # Check if the directory exists and is writable
    local dir="$(dirname "$file")"
    if [[ ! -d "$dir" ]]; then
        error "Output directory does not exist: $dir"
    fi

    if [[ ! -w "$dir" ]]; then
        error "Output directory is not writable: $dir"
    fi

    # Check if output file would overwrite something important
    if [[ -f "$file" && ! -w "$file" ]]; then
        error "Output file exists but is not writable: $file"
    fi
}

# Parse command line arguments
main() {
    local output_file="$DEFAULT_OUTPUT"

    while [[ $# -gt 0 ]]; do
        case $1 in
            -h|--help)
                show_usage
                exit 0
                ;;
            -v|--version)
                show_version
                exit 0
                ;;
            --output)
                if [[ $# -lt 2 ]]; then
                    error "--output requires a filename argument"
                fi
                if [[ "$2" =~ ^- ]]; then
                    error "--output requires a filename argument (got option: $2)"
                fi
                output_file="$2"
                shift 2
                ;;
            --output=*)
                output_file="${1#*=}"
                if [[ -z "$output_file" ]]; then
                    error "--output= requires a filename argument"
                fi
                shift
                ;;
            *)
                error "Unknown option: $1"
                ;;
        esac
    done

    # Validate the output file
    validate_output_file "$output_file"

    # Perform the build
    build_suitey "$output_file"
}

# Run the main function with all arguments
main "$@"
