#!/usr/bin/env bats

load 'test_helper/bats-support/load'
load 'test_helper/bats-assert/load'

setup() {
    # Ensure we're in the project root
    # Find the project root by going up from the test file location
    local test_dir="$(cd "$(dirname "$BATS_TEST_FILENAME")" && pwd)"
    local project_root="$(cd "$test_dir/../../.." && pwd)"
    cd "$project_root"

    # Source the build.sh functions
    source build.sh

    # Create a temporary directory for test builds
    export TEST_BUILD_DIR="$(mktemp -d)"
}

teardown() {
    # Clean up temporary build directory
    if [[ -n "$TEST_BUILD_DIR" && -d "$TEST_BUILD_DIR" ]]; then
        rm -rf "$TEST_BUILD_DIR"
    fi
}

@test "validate_build_output checks Bash syntax validity" {
    local valid_file="$TEST_BUILD_DIR/valid.sh"
    cat > "$valid_file" << 'EOF'
#!/usr/bin/env bash
echo "valid script"
EOF

    local invalid_file="$TEST_BUILD_DIR/invalid.sh"
    echo 'invalid syntax (' > "$invalid_file"

    run validate_build_output "$valid_file"
    assert_success

    run validate_build_output "$invalid_file"
    assert_failure
}

@test "validate_build_output verifies script is executable" {
    local output_file="$TEST_BUILD_DIR/test.sh"
    cat > "$output_file" << 'EOF'
#!/usr/bin/env bash
echo "test script"
EOF

    run validate_build_output "$output_file"
    assert_success

    # File should be executable after validation
    assert [ -x "$output_file" ]
}

@test "validate_build_output checks reasonable file size" {
    local small_file="$TEST_BUILD_DIR/small.sh"
    echo "#!/bin/bash" > "$small_file"

    local large_file="$TEST_BUILD_DIR/large.sh"
    cat > "$large_file" << 'EOF'
#!/usr/bin/env bash

# Suitey - Cross-platform test runner
# This file was generated by build.sh - do not edit directly

# Version: 0.1.0
# Built: 2024-01-08 13:00:00 UTC
# Built on: Linux 6.8.0

main() {
    echo "Suitey v0.1.0"
    echo "Build system functional - ready for implementation"
    echo ""
    echo "Usage: $0 [command] [options]"
    echo ""
    echo "Commands:"
    echo "  --help, -h    Show help"
    echo "  --version, -v Show version"
}

main "$@"
EOF

    run validate_build_output "$small_file"
    assert_failure

    run validate_build_output "$large_file"
    assert_success
}

@test "validate_build_output verifies expected functions are present" {
    local output_file="$TEST_BUILD_DIR/test.sh"
    cat > "$output_file" << 'EOF'
#!/usr/bin/env bash

# Suitey - Cross-platform test runner
# This file was generated by build.sh - do not edit directly

# Version: 0.1.0
# Built: 2024-01-08 13:00:00 UTC
# Built on: Linux 6.8.0

check_bash_version() {
    echo "function exists"
}

main() {
    echo "main function"
}

main "$@"
EOF

    run validate_build_output "$output_file"
    assert_success
}

@test "validate_build_output checks filesystem isolation compliance" {
    local output_file="$TEST_BUILD_DIR/test.sh"
    cat > "$output_file" << 'EOF'
#!/usr/bin/env bash

# Suitey - Cross-platform test runner
# This file was generated by build.sh - do not edit directly

# Version: 0.1.0
# Built: 2024-01-08 13:00:00 UTC
# Built on: Linux 6.8.0

main() {
    echo "filesystem isolation test"
}

main "$@"
EOF

    run validate_build_output "$output_file"
    assert_success
}

@test "validate_build_output ensures script runs without errors" {
    local output_file="$TEST_BUILD_DIR/test.sh"
    cat > "$output_file" << 'EOF'
#!/usr/bin/env bash

# Suitey - Cross-platform test runner
# This file was generated by build.sh - do not edit directly

# Version: 0.1.0
# Built: 2024-01-08 13:00:00 UTC
# Built on: Linux 6.8.0

main() {
    echo "Suitey v0.1.0"
    echo "Build system functional - ready for implementation"
}

main "$@"
EOF

    run validate_build_output "$output_file"
    assert_success

    # Test that the script actually runs
    run "$output_file"
    assert_success
    assert_output --partial "Suitey v"
}

@test "validate_build_output verifies shebang correctness" {
    local correct_file="$TEST_BUILD_DIR/correct.sh"
    cat > "$correct_file" << 'EOF'
#!/usr/bin/env bash
echo "correct shebang"
EOF

    local incorrect_file="$TEST_BUILD_DIR/incorrect.sh"
    cat > "$incorrect_file" << 'EOF'
#!/bin/bash
echo "incorrect shebang"
EOF

    run validate_build_output "$correct_file"
    assert_success

    run validate_build_output "$incorrect_file"
    assert_failure
}
