#!/usr/bin/env bats

load '../test_helper/bats-support/load'
load '../test_helper/bats-assert/load'

setup() {
    # Ensure we're in the project root
    # Find the project root by going up from the test file location
    local test_dir="$(cd "$(dirname "$BATS_TEST_FILENAME")" && pwd)"
    local project_root="$(cd "$test_dir/../../.." && pwd)"
    cd "$project_root"

    # Source the build.sh functions
    source build.sh
}

@test "bundle_source_files creates bundled script with discovered files" {
    local output_file="/tmp/test_bundle_$$.sh"

    run bundle_source_files "$output_file"
    assert_success

    # Verify output file was created
    assert [ -f "$output_file" ]
    assert [ -s "$output_file" ]  # Not empty

    # Verify it contains expected content
    run grep "Suitey - Cross-platform test runner" "$output_file"
    assert_success

    run grep "Version:" "$output_file"
    assert_success

    # Verify it contains source files
    run grep "check_bash_version" "$output_file"
    assert_success

    # Clean up
    rm -f "$output_file"
}

@test "create_bundle_header adds correct header information" {
    local temp_file="/tmp/test_header_$$.sh"

    run create_bundle_header "$temp_file"
    assert_success

    # Verify header content
    run grep "#!/usr/bin/env bash" "$temp_file"
    assert_success

    run grep "Suitey - Cross-platform test runner" "$temp_file"
    assert_success

    run grep "Version:" "$temp_file"
    assert_success

    run grep "Built:" "$temp_file"
    assert_success

    # Clean up
    rm -f "$temp_file"
}

@test "include_source_files adds files in correct order" {
    local temp_file="/tmp/test_include_$$.sh"
    echo "#!/bin/bash" > "$temp_file"

    # Create test source files
    local test_file1="/tmp/source1_$$.sh"
    local test_file2="/tmp/source2_$$.sh"

    echo '# Source file 1' > "$test_file1"
    echo 'function test1() { echo "test1"; }' >> "$test_file1"

    echo '# Source file 2' > "$test_file2"
    echo 'function test2() { echo "test2"; }' >> "$test_file2"

    run include_source_files "$temp_file" "$test_file1" "$test_file2"
    assert_success

    # Verify files are included in order
    run grep -A 5 -B 5 "Source file 1" "$temp_file"
    assert_success

    run grep -A 5 -B 5 "Source file 2" "$temp_file"
    assert_success

    # Verify functions are included
    run grep "function test1" "$temp_file"
    assert_success

    run grep "function test2" "$temp_file"
    assert_success

    # Clean up
    rm -f "$temp_file" "$test_file1" "$test_file2"
}

@test "create_bundle_footer adds proper main execution" {
    local temp_file="/tmp/test_footer_$$.sh"

    run create_bundle_footer "$temp_file"
    assert_success

    # Verify footer contains main execution
    run grep 'main "$@"' "$temp_file"
    assert_success

    # Clean up
    rm -f "$temp_file"
}

@test "validate_bundle checks bundled script validity" {
    local valid_file="/tmp/test_valid_$$.sh"
    cat > "$valid_file" << 'EOF'
#!/usr/bin/env bash

# Suitey - Cross-platform test runner
# This file was generated by build.sh - do not edit directly

# Version: 0.1.0
# Built: 2024-01-08 13:00:00 UTC
# Built on: Linux 6.8.0

echo "Suitey v0.1.0"
echo "Build system test - functionality not yet implemented"
echo ""
echo "Usage: $0 [command] [options]"
echo ""
echo "Commands:"
echo "  --help, -h    Show help"
echo "  --version, -v Show version"
EOF

    local invalid_file="/tmp/test_invalid_$$.sh"
    echo 'invalid syntax (' > "$invalid_file"

    run validate_bundle "$valid_file"
    assert_success

    run validate_bundle "$invalid_file"
    assert_failure

    # Clean up
    rm -f "$valid_file" "$invalid_file"
}
